import localFont from "next/font/local";
import "./globals.css";
import "./custom.css";
import { Toaster } from "@/components/ui/toaster"
import SessionWrap from "@/context/SessionWrap";
import Loading from "./components/Loading";
import { Suspense } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Tiffinboxes a indian food delivery service",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  `}
      >
        <SessionWrap >
        <Suspense fallback={<Loading />}>
          {children}
          <Toaster />
          </Suspense>
          </SessionWrap>
      </body>
    </html>
  );
}
